on:
  push:
jobs:
  third-job:
    runs-on: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Check node version
        run: node --version
      - name: Check npm version
        run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node index.js
